# http://lmjohns3.com/2015/06/using-travis-ci-with-miniconda-scipy-and-nose.html

language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.4'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    dist: trusty
    sudo: false
    python: 3.6-dev
cache:
  apt: true
  pip: true
  ccache: true
  directories:
  
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install:
# - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" && "$TRAVIS_PYTHON_VERSION" == "3.5" ]];
  # then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  # bash miniconda.sh -b -p $HOME/miniconda;
  # export PATH="$HOME/miniconda/bin:$PATH";
  # conda update --yes conda; 
  # fi
# - pip install matplotlib
# - pip install sphinx
# - pip install numpydoc
# - pip install sphinx_rtd_theme
install:
- pip install -qq --upgrade pip setuptools wheel
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" && "$TRAVIS_PYTHON_VERSION" == "3.5" ]];
  then pip install -qq --only-binary=numpy,scipy numpy;
  fi
  # then conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy;
  # fi
- pip install pytest-cov
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]];
  then pip install codecov;
  fi
- python setup.py install
# - python setup.py sdist
# - cd $TRAVIS_BUILD_DIR/docs/
# - sphinx-apidoc -o ./source ../sciplot
# - make html
# - pip uninstall -y sciplot-pyqt
# - cd $TRAVIS_BUILD_DIR
# - python setup.py install
script:
- pytest --cov=./

after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]];
  then codecov;
  fi
# branches:
#   only:
#   - master
#   - dev

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/ # Remove this line for official deployment
  user: ccampjr
  password:
    # TestPyPi password 
    secure: IUJ6pcXgJhB4FKQrmdjxYaaeUgO1J9dWqt2Xr+VSJzARvC7qxqkR9y/fhBaXKZ0IPnOYcnP2fyYlVztJ5d3iMFA6Uq+JFJXrLEV+81Ntp23KCCqer1347tC/3dWZgZD+b4Cd2Z5SUd/3k1BxpQkzkFqSZdaiGujv5bdrFcQLtMTacBRiWjMR8IBz4L0HO98BenfRqfCc+Gnxw2HZPI6/aXDYbTiqJCFxn1HAz4ffcwHIrLU2GK/367ojh6THeFGqV6IP1JOO0I8BJXWlFueL9I5HiyxzHKO/7md3yn1lSvuJAZ4kzbzUktw+DVvqQ6Go1fjvrz1s8g0iUHDgRnFCoKZU1tdccxy/1YhoF9GnOISSA6QBRTgNVX6mNFyizabqTnKZbgWkBlzWgzVEswX4+vOXvcBhBOM0O+mCI5gt2Dp8wKNiIZ+21VHVHi6jlXd2IYODm2jV9ezyhjK2PE4h8MDaBvNDxv7rc4u3MGQL6yKwuBXWOVt/QNPc2LdOtKmBf14QYYnvVCHIbuEZ//7Ls6Rw7OvhlQB+l0cQQyAq0LG9C6NeP+yoe6qJZD4rHUIBDLZ9aTY5G+F+lXB1/8+cK9NmOvxWH6C2tqV4fmbHrb9pjkIq9ugsFli4NZZV/+Hr1Fj8nRhdIM+kOVX/p2+kp1gS3nl+Mg1Qenniw7Mld2U=
  on:
    branch: prerelease
    tags: true
    python: 3.6

    
  provider: pypi
  user: ccampjr
  password:
    # PyPi
    secure: N8hswlUiEnQCkEamgnDoCkdsIuGPwmHRe0/bE5cPcdas+92wzQl/9FyvBCN3EKjOTxCDMPPPTzOsaJo/RfIPuTKiKsOZCsqLR2rKW3rGrHUWlXIhW6FjCBvwIlqpbvwhMA9Soiv+XlsRfEpEIpj8DJeLYAXUb8hmuQNLP/PHPwGm33VCOEYPhWUX8ypCTpkPxzYA2eM9uBzTUYiCHINlYkDMqpmIPiBVHw/N/s2UDpSFRpCv5XkIpA3LFPhiY9LQxbTMAVD4kmnJ8e/8FJ7nRBnDH5S9dEPBx6B2QCMTEULWzxlyy8r8iGg1HmtR2WI2KxnikRnFmXXEsxE76vAQfFIi8uzXVXYM6MEd4CaPkRKWnC8Tikw43f/2lPJjTD7h4T30uH+mWDeWaWYBwnZ/091UzgZieiuL1e1rYIZZoozmIE5CQps3HQaO0DPkbMASLbOXehDwGEIJyJNwP/bFCSE1aopevGa/Do+y+YX+OdciEkvGwvewfKiAw5vpGl8UkvJo8/CEl7L1OQWo/Rr2UOYFb2BNcRi8Oox7515sNIdyM2QBMbJdhEoYweHenBY4rDlWl+ZkBJk0zDUaYJZPJQbkVQXuanxIfSlgJHtBMb9cz1BWMTd/cXPXNrABgmxAG6EVPU//NPUPXxU71xvbCH1Lw3w7FoOIs18L1b4loyo=
  on:
    branch: master
    tags: true
    python: 3.6